app:
  port: 3000
  name: "NPR Potluck"
  pub_dir: "/public"
  tmp_dir: "/tmp"
  max_resources_num: 1
  submission_msg_char_limit: 700
  cookie_secret: "your secret key salt goes here"
mysql:
  host: localhost
  user: root
  pass: password
  database: potluck
aws:
  accountID: AmazonAccountId
  accessKeyId: AmazonAWSAccessKeyId
  secretKey: AmazonAWSSecretAccessKey
  bucket: AmazonS3Bucket
  cacheTTL: 86400
  cdnDomain: "potluckstage.s3.amazonaws.com"
  thumbsCDNDomain: "CDN_Domain_Pointing_To_Node_Origin"
  S3region: US_EAST_1
  SQSregion: US_EAST_1
  SQSQueueName: potluck_stage
